<a href="https://colab.research.google.com/github/arpit-devop/machine-learning-assignment/blob/main/ml1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)


[5 4 6 3 2 1]


In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Method 1: flatten()
flat1 = array1.flatten()

# Method 2: ravel()
flat2 = array1.ravel()

print(flat1)
print(flat2)


[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(np.array_equal(arr1, arr2))
print(np.all(arr1 == arr2))


True
True


In [ ]:
# i.
x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_freq_val = values[np.argmax(counts)]
indices = np.where(x == most_freq_val)[0]
print("Most frequent:", most_freq_val)
print("Indices:", indices)

# ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_freq_val = values[np.argmax(counts)]
indices = np.where(y == most_freq_val)[0]
print("Most frequent:", most_freq_val)
print("Indices:", indices)


Most frequent: 1
Indices: [0 5 7 8 9]
Most frequent: 1
Indices: [0 1 2]


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
sum_all = gfg.sum()

# ii. Sum row-wise
sum_row = gfg.sum(axis=1)

# iii. Sum column-wise
sum_col = gfg.sum(axis=0)

print("Sum all:", sum_all)
print("Sum row-wise:", sum_row)
print("Sum column-wise:", sum_col)


Sum all: 45
Sum row-wise: [[14]
 [16]
 [15]]
Sum column-wise: [[20  9 16]]


In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])

# i. Sum of diagonal elements
sum_diag = np.trace(n_array)

# ii. Eigen values
eig_vals, eig_vecs = np.linalg.eig(n_array)

# iii. Eigen vectors
# eig_vecs already calculated above

# iv. Inverse of matrix
inv_matrix = np.linalg.inv(n_array)

# v. Determinant
det_matrix = np.linalg.det(n_array)

print("Sum diagonal:", sum_diag)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:", eig_vecs)
print("Inverse matrix:", inv_matrix)
print("Determinant:", det_matrix)


Sum diagonal: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse matrix: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [ ]:
# i.
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

mul1 = np.matmul(p, q)
cov1 = np.cov(p, q)

print("Multiplication 1:\n", mul1)
print("Covariance 1:\n", cov1)

# ii.
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

mul2 = np.matmul(p2, q2)

cov2 = np.cov(p2.flatten(), q2.flatten())

print("Multiplication 2:\n", mul2)
print("Covariance 2:\n", cov2)


Multiplication 1:
 [[16 19]
 [26 31]]
Covariance 1:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
Multiplication 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance 2:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])


inner_prod = np.inner(x, y)

outer_prod = np.outer(x.flatten(), y.flatten())

from itertools import product
cartesian_prod = np.array([np.concatenate((i,j)) for i,j in product(x, y)])

print("Inner product:\n", inner_prod)
print("Outer product:\n", outer_prod)
print("Cartesian product:\n", cartesian_prod)


Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


In [ ]:
array = np.array([[1, -2, 3],[-4, 5, -6]])

# i. Element-wise absolute value
abs_array = np.abs(array)

# ii. Percentiles (25th, 50th, 75th)
percentiles_flat = np.percentile(array, [25, 50, 75])
percentiles_col = np.percentile(array, [25, 50, 75], axis=0)
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)

# iii. Mean, Median, Std dev
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("Absolute value:\n", abs_array)
print("Percentiles flat:", percentiles_flat)
print("Percentiles col:\n", percentiles_col)
print("Percentiles row:\n", percentiles_row)
print("Mean flat:", mean_flat)
print("Median flat:", median_flat)
print("Std flat:", std_flat)
print("Mean col:", mean_col)
print("Median col:", median_col)
print("Std col:", std_col)
print("Mean row:", mean_row)
print("Median row:", median_row)
print("Std row:", std_row)


Absolute value:
 [[1 2 3]
 [4 5 6]]
Percentiles flat: [-3.5 -0.5  2.5]
Percentiles col:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean flat: -0.5
Median flat: -0.5
Std flat: 3.8622100754188224
Mean col: [-1.5  1.5 -1.5]
Median col: [-1.5  1.5 -1.5]
Std col: [2.5 3.5 4.5]
Mean row: [ 0.66666667 -1.66666667]
Median row: [ 1. -4.]
Std row: [2.05480467 4.78423336]


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)

print("Floor:", floor_vals)
print("Ceiling:", ceil_vals)
print("Truncated:", trunc_vals)
print("Rounded:", round_vals)


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_arr = np.sort(array)

# ii. Indices of sorted array
indices_sorted = np.argsort(array)

# iii. 4 smallest elements
four_smallest = np.partition(array, 4)[:4]

# iv. 5 largest elements
five_largest = np.partition(array, -5)[-5:]

print("Sorted array:", sorted_arr)
print("Indices of sorted array:", indices_sorted)
print("4 smallest elements:", four_smallest)
print("5 largest elements:", five_largest)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]


In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
int_elements = array[array == array.astype(int)]

# ii. Float elements only (elements which are not integers)
float_elements = array[array != array.astype(int)]

print("Integer elements:", int_elements)
print("Float elements:", float_elements)


Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


In [ ]:
from google.colab import files
uploaded = files.upload()
img_path = next(iter(uploaded))


Saving Screenshot 2025-08-04 114214.png to Screenshot 2025-08-04 114214 (1).png


In [ ]:
arr = img_to_array(img_path)


In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    # Check if grayscale or RGB
    if arr.ndim == 2:
        # Grayscale image
        np.savetxt('grayscale_image.txt', arr, fmt='%d')
        print("Saved as grayscale_image.txt")
    elif arr.ndim == 3 and arr.shape[2] == 3:
        # RGB image: Save each channel as separate file or flatten
        arr_reshaped = arr.reshape(-1, 3)
        np.savetxt('rgb_image.txt', arr_reshaped, fmt='%d')
        print("Saved as rgb_image.txt (flattened per pixel)")
    else:
        raise Exception("Unsupported image format")
    return arr
